# Generated by Django 4.0.6 on 2022-07-19 02:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('profissional', models.CharField(max_length=80, verbose_name='Nome do profissional')),
                ('data_exame', models.DateField(verbose_name='Data do exame')),
                ('peso', models.DecimalField(decimal_places=3, max_digits=11, verbose_name='Peso (Kg)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Altura (m)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.paciente', verbose_name='Paciente')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
